name: My First Workflow

on: push


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome Message
              run: |
               echo "Myfirst github actions job"
               ls -ltar
               cat README.md
               
            - name: Generate Ascii artwork
              run: |
               cowsay -f dragon "Run for a cover, I am a DRAGON...RAWR " >> dragon.txt


   #         - name: List files
   #           run: ls
            
   #         - name: Read files
   #           run: cat README.md


              