name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Run ls
              run: ls -ltar

            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Welcome Message
              run: |
               echo "Myfirst github actions job"
               ls -ltar
               cat README.md
               




              
