name: Multi Jobs Workflow

on: push

jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay program 
              run: sudo apt-get install cowsay -y
             
            - name: Generate Ascii artwork
              run: |
               cowsay -f dragon "Run for a cover, I am a DRAGON...RAWR " >> dragon.txt
             
            - name: Upload dragon.txt file 
              uses: actions/upload-artifact@v4
              with:
                name: my-dragon-file
                path: dragon.txt

    Test_job_2:
        needs: Build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download dragon.txt file 
              uses: actions/download-artifact@v4
              with:
                name: my-dragon-file


                     
            - name: Test File Exist
              run: grep -i "dragon" dragon.txt
    Deploy_job_3:
        needs: [Test_job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Download dragon.txt file 
              uses: actions/download-artifact@v4
              with:
                name: my-dragon-file

            - name: Read File 
              run: cat dragon.txt
                     
            - name: Deploy in to Server
              run: echo "Deploying in to server"        
                     



              