name: Multi Jobs Workflow

on: push

jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay program 
              run: sudo apt-get install cowsay -y
             
            - name: Generate Ascii artwork
              run: |
               cowsay -f dragon "Run for a cover, I am a DRAGON...RAWR " >> dragon.txt
             
            - name: Sleep for 30 seconds 
              run: sleep 30
    Test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10 seconds 
              run: sleep 10
                     
            - name: Test File Exist
              run: grep -i "dragon" dragon.txt
    Deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Read File 
              run: cat dragon.txt
                     
            - name: Deploy in to Server
              run: echo "Deploying in to server"        
                     



              